#!/usr/bin/env bash
# Command to make an nginx server listen on port 80
apt-get -y update
apt-get -y install nginx
sudo rm /nginx/sites-enable/default
sudo In -sf /etc/Nginx/sites-avalable/default /etc/Nginx/sites-enabled/default
sudo service nginx start 
